### ISSUE TITLE
I want the AaC package deployed to pypi

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#114]
As an AaC user, I want the packaged deployed to pypi, so that I can install it in my environments via pip.

NOTE: This issue should be completed after #109 so that any package deployed to pypi has the core AaC spec packaged correctly.

AC:

- [x] The deploy job is moved from the main-branch.yaml file to a manual workflow job
- [x] The deploy job is only trigger manually
- [x] The deploy job publishes the aac package to pypi.
- [ ] The aac package can be installed via `pip install aac`

**Comment by jondavid-black** [comment]
FYI...I've done this manually already and reserved the 'aac' name in pypi.  The pypi api key is already captures as a secret in the repo.  There is some commented out code in the GitHub actions workflow to do this.  I'd recommend publishing be done in a different workflow than CI.

**Comment by Coffee2Bits** [comment]
> FYI...I've done this manually already and reserved the 'aac' name in pypi. The pypi api key is already captures as a secret in the repo. There is some commented out code in the GitHub actions workflow to do this. I'd recommend publishing be done in a different workflow than CI.
> 
> It also looks like #77 should be done before this (or maybe there's some duplication here?).

I may be being too pedantic here; I agree that the CI _shouldn't_ deploy our artifacts, that's what our CD workflow should be. Perhaps this story would be better described as producing the project's Continuous Delivery workflow -- which includes at least a mostly automated deployment workflow. 

There is some overlap with #77, but I felt that getting our AaC distributions done and at least mostly automated was important before we consider asking others to use the package.

**Comment by Coffee2Bits** [comment]
WE can automate a semantic version in the git tags and automate the bumping of them with a GHA like this:
https://github.com/marketplace/actions/semantic-version-bump-per-branch-and-tag

**Comment by Coffee2Bits** [comment]
Package is uploaded to PyPI
[AaC v0.0.4](https://pypi.org/project/aac/0.0.4/)
