### ISSUE TITLE
Update pipeline to run core plugin tests

### ISSUE THREAD

**Issue by cvchaparro** [jondavid-black/AaC#117]
As an AaC user, I want the pipeline to run core plugin tests so that I can have
confidence that changes won't break my workflow.

## AC
- [ ] The pipeline runs tests for each plugin in the `plugins/` directory.
- [ ] Code coverage for the plugins is included in the main coverage report\*.

\* This is the ideal case. If the coverage report can't be updated to include
code coverage for the plugins, create a new coverage report for each plugin and
store the artifact in the pipeline. We will figure out how to consolidate it in
a future story. The way I would recommend trying this is looking into [`tox`
environments][1].

## Notes

If needed to do the coverage reporting for plugins, consider the following AC to be added:

- [ ] Add a `tox.ini` to each of the plugin projects (base it off of the main
      project `tox.ini` file) that includes unit testing, code coverage, and
      linting (at a minimum).

[1]: https://tox.wiki/en/latest/config.html#tox-environments

**Comment by Coffee2Bits** [comment]
I've been trying to think of a good way to handle the plugins and their workflows inside of the AaC project, and I think you're right that the best way forward at the moment is to just try adding them to the current project flow. 

Any other solutions I could come up with like git submodules, disparate projects for plugins, etc all add a lot of management overhead and noise. I think this is the simplest approach to take and will help us determine if we need a more complex solution.

**Comment by Coffee2Bits** [comment]
Closing in favor of #140.
