### ISSUE TITLE
Relocate the GenPlugin and GenJSON plugins

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#121]
The GenJSON and GenPlugin plugins were our first two plugins, and we've learned a lot since -- it's time we applied that back to these plugins. 

I'm happy to treat gen-plugin as a special child, but I don't there is a technical reason for genplugin not to live with the rest of the plugins, especially once we get their testing environments hooked up in the CI workflow.

AC:
- [ ] GenJSON plugin is standardized
  - [ ] Moved to the plugins directory
  - [ ] An AaC yaml file is created for the plugin
  - [ ] The plugin is refreshed via the genplugin plugin
  - [ ] Any tests are moved into the new plugin's tests directory
- [ ] GenPlugin plugin is standardized
  - [ ] Moved to the plugins directory
  - [ ] An AaC yaml file is created for the plugin
  - [ ] The plugin is refreshed via the genplugin plugin
  - [ ] Any tests are moved into the new plugin's tests directory

**Comment by jondavid-black** [comment]
I don't think we can do this until we improve our plugin CI and delivery/publication.  I keep wondering if we should perhaps do the opposite and move some of the plugins we've made into the main src folder so they become part of the core wheel publication.  The question haunting me: if a used does 'pip install aac' will they get something they feel is valuable or will they have to know to install a bunch of other plugins?  Knowing that plugins exist and you have to install them doesn't seem very approachable for a novice AaC user.

**Comment by Coffee2Bits** [comment]
This is no longer necessary because of #140
