### ISSUE TITLE
Fix linter warnings

### ISSUE THREAD

**Issue by cvchaparro** [jondavid-black/AaC#124]
We are starting to accumulate several linter warnings that should be addressed and controls put in place to make sure we aren't introducing more linter warnings.

## AC:

- [x] Fix linter warnings
  - [x] If the warning is a `TODO` comment for us - i.e. not in a Jinja2 template - then create an issue out of the comment and delete it.
  - [x] For all other warnings, address them appropriately.
- [x] Update the pipeline to fail the linting phase if a certain threshold of warnings are found (i.e. I think this would mean removing the `--exit-zero` flag)

**Comment by Coffee2Bits** [comment]
This has also been bothering me. My first inclination was to implement a script that wraps the flake8 command and compares the violation count to a threshold that we define. Then we could leverage the threshold to drop the violations over time, like we raised the code coverage. Problem is that I've not been successful in creating a one-liner that'll grab the count value from flake and return 0 or 1 based on whether the count exceeds the threshold number, and I'm not excited at adding a script directory just for a single flake8 script, but that would probably be a quick way forward without fixing everything at once.
