### ISSUE TITLE
Add plugin installation functional tests

### ISSUE THREAD

**Issue by cvchaparro** [jondavid-black/AaC#135]
In #99 we needed to test plugin installation but I wasn't able to get it
working. The purpose of this task is to add an automated test that simulates the
installation of a plugin and ensures the commands, extensions, etc are available
after the installation.

## AC

- [ ] At least one automated test exists that installs a plugin and confirms
      it's extensions, commands, etc are available to the `aac` module.

**Comment by Coffee2Bits** [comment]
This scope should be limited to 3rd party plugins since 1st party plugins are being tested as part of the functional tests, and 1st party plugins can't be installed by the user.

**Comment by Coffee2Bits** [comment]
We're performing this in our CI/CD pipelines now.
