### ISSUE TITLE
I want the LSP integrated with the VSCode Extension

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#141]
As an AaC user, I want the LSP integrated with the VSCode Extension, so that I can have linting, errors, references, refactoring, and all the other loveliness that comes with IDE language support.

Is blocked by: #187

### AC:

- [x] The LSP features are activated when AaC files are detected by VSCode
- [x] The plugin provides basic auto-completion capabilities for top-level AaC elements (i.e. `model`, `usecase`, etc).

### Notes

From this [discussion](https://github.com/jondavid-black/AaC/discussions/125#discussioncomment-1759560).

Here's an example [LSP plugin repository](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample).

Thinking about the overlap between the validator and what the LSP will need, we may need to retool some of the validation functionality into an AaC language module that'll also be used by the LSP.

LSP Functionality reference can be found [here](https://microsoft.github.io/language-server-protocol/specifications/specification-current/). LSP functionality that we'll need to add to the Validator/Future Language Module:
* Error/Warning line(s)/column(s) (Some range for our feedback)
* Linting will be based on this
* Completion
* Reference names
* Root types
* Defined types
* References
* Refactor/renaming will be based on this
* Jump to will be based on this
* Implementations will be based on this
* Definitions will be based on this

**Comment by jondavid-black** [comment]
I came across the ansible language server and thought it may provide some useful insights as it is YAML based.
https://github.com/ansible/ansible-language-server

**Comment by jondavid-black** [comment]
Another interesting project to consider is UMLet.  I haven't been able to get my head around how it actually works, but it appears to maintain a single code base supporting a stand-alone UI and a IDE extensions for Eclipse and VSCode.
https://github.com/umlet/umlet

**Comment by Coffee2Bits** [comment]
Rolling to Sprint 2 (AD)
