### ISSUE TITLE
Rename the Plugin definitions hookname

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#145]
Rename the Plugin definitions hookname since it no longer only returns the plugin model's extensions. 

https://github.com/jondavid-black/AaC/blob/2e36baa437857c4b3a591c70b9e2a997e8ef42ff/src/aac/hookspecs.py#L16-L23

AC:
- [x] Change `get_base_model_extensions` to `get_plugin_aac_definitions`  
- [x] All existing plugins are updated to use the new function name
- [x] The genplugin template `plugin.py.jinja2` to use the new function name
- [x] Update the genplugin test to check for the new function name in the generated files.
- [x] Update all `get_plugin_aac_definitions` function docstring summaries from `Return data and ext definitions to apply to the AaC base.`  to `Returns the plugin's AaC definitions.`

**Comment by GustavoGB** [comment]
Hi! Can I try this one :) ?

**Comment by Coffee2Bits** [comment]
> Hi! Can I try this one :) ?

Hi Gustavo! 👋 

We're currently using some Agile ceremonies like sprints and sprint planning to align the team on issues and issue refinement. I haven't had any other team members look over this issue yet, but I can arrange that.

We're happy to hear that you found the project interesting enough to want to contribute! Do you mind if I ask how you heard about the project and what drew you into it?

**Comment by GustavoGB** [comment]
Hi Alex! hope everything is fine with you. I Wanted to start my journey contributing on open source projects and I liked what it's beeing implemented here. I will work on this today and try to make the PR as soon as I can! Cheers :)
