### ISSUE TITLE
Handle plugin execution results consistently

### ISSUE THREAD

**Issue by cvchaparro** [jondavid-black/AaC#147]
## Description

As a plugin developer, I want to be able to signal exception conditions that occur in my plugin without effecting the rest of the system so that errors can be propogated to the CLI/GUI and displayed to the user.

## AC

- [x] A class exists that represents a plugin execution result and it is available for use by all plugins.
- [x] GenPlugin is updated to have plugin commands return an instance of this class.
- [x] The CLI is updated to handle this returned execution result object.
  - [x] For success, print/log a success message.
  - [x] For failure, print/log a failure message and exit with non-zero status code.
- [x] At a minimum, the class has some way to provide the following information to whatever receives the result:
  - [x] `name`: the name of the plugin whose execution result is being handled.
  - [x] `status_code`: the status code to return from the CLI, for example.
  - [x] `errors`: a list of error messages that can be provided to the user so they know what went wrong.
- [x] The `status_code` is not just a number that users must know. That is, we don't want something like this:
    ```python
    result = command.callback(**kwargs)
    if result.status_code != 0:
        print('failure')
    ```
    Rather, do something like this:
    ```python
    result = command.callback(**kwargs)
    if result.execution_failed()
        print('failure')
    ```
    Or even like this:
    ```python
    result = command.callback(**kwargs)
    if result.status_code != PluginExecutionStatusCode.SUCCESS:
        print('failure')
    ```
- [x] If a plugin fails in the pipeline, the pipeline fails.

**Comment by Coffee2Bits** [comment]
Added two sub-bullets for some extra clarity on what we're expecting.
```
* The class contains an error code status
* The class contains a list of errors
```

I think this is a pretty important issue for us to complete since it'll help us improve the testability of plugins as well as the benefits of running them in the UI that you pointed out. I've gone ahead and added it to sprint 6 -- but we can discuss it during planning.

**Comment by cvchaparro** [comment]
Yeah, I think it is important. That said, I think those bullets are covered by AC item 4, no?

**Comment by Coffee2Bits** [comment]
> Yeah, I think it is important. That said, I think those bullets are covered by AC item 4, no?

Yeah, I'm an idiot. I've removed them.

**Comment by cvchaparro** [comment]
For the last AC, see: https://github.com/jondavid-black/AaC/runs/4722270887?check_suite_focus=true#step:10:1
