### ISSUE TITLE
Refactor the _get_all_extension_errors function to reduce complexity

### ISSUE THREAD

**Issue by cvchaparro** [jondavid-black/AaC#151]
## Description

As a maintainer, I want `_get_all_extension_errors` refactored to reduce complexity so that I can understand how to address bugs or add new functionality to the validator.

## AC

- [ ] The `# noqa: C901` linter comment is removed from the `validator.py` file.
- [ ] The `_get_all_extension_errors` function is broken into smaller functions.

## Notes

- The real test, here, will be whether the pipeline passes after removing the `noqa` comment.

**Comment by Coffee2Bits** [comment]
Do we need to do this before the validator rewrite?

**Comment by cvchaparro** [comment]
Not necessarily. If it saves us re-work I'm fine with postponing it until afterwards.
