### ISSUE TITLE
Identify Functional Steps to Implement a general VSCode Plugin for AaC

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#176]
Identify the technical steps to produce a general VSCode plugin for AaC. Focus on features/functionality in the [common capabilities](https://code.visualstudio.com/api/extension-capabilities/common-capabilities) and [workbench extensions](https://code.visualstudio.com/api/extension-capabilities/extending-workbench).

AC:
- [x] Document any language compatibility issues and solutions
- [x] Document the integration information (Documentation, examples, dependencies)
- [x] Provide several example use cases of how implementing this plugin would help the user (example use cases)
- [x] Document high-level steps to implement an AaC VSCode Plugin (what needs to be done before we can write the code)
- [x] Documentation is stored in a new wiki page

**Comment by jondavid-black** [comment]
I've been experimenting with this and dropping some breadcrumbs in the discussion on using VS Code as the UI.  You may find useful nuggets there.

**Comment by Coffee2Bits** [comment]
Wiki page can be found here: https://github.com/jondavid-black/AaC/wiki/VSCode-Plugin-Implementation-Notes

**Comment by Coffee2Bits** [comment]
> I've been experimenting with this and dropping some breadcrumbs in the discussion on using VS Code as the UI. You may find useful nuggets there.

It was a great help! I really appreciate it.
