### ISSUE TITLE
Implement Language Server Protocol

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#187]
Implement the Language Server Protocol in the AaC package in preparation for integration with the language server features for a VSCode Extension. The goal is to prepare the AaC package for jumping into AaC Language Server (ALS) + VSCode Extension stories.

References:
[Language Server Protocol Specification](https://microsoft.github.io/language-server-protocol/specification)
[Pygls](https://github.com/openlawlibrary/pygls) - Python Language Server Library (Recommended to use for this story)

## AC:
- [x] Add a new command that runs the AaC language server
  - [x] Add an optional argument to set the port to for the ALS to listen on
- [x] Identify the overlap between validation features and ALS functions
  - [x]  Document a solution on providing functionality such as verifying model references to the validator and the ALS
- [x]  Add a simple event handler that prints requests received by the server

**Comment by Coffee2Bits** [comment]
Rolling to Sprint 9

**Comment by cvchaparro** [comment]
I wrote a brief summary of the overlap between the validator and the LSP server. It can be found [here](https://github.com/jondavid-black/AaC/wiki/Overlap-Between-Validator-and-LSP-Server#lsp-server).
