### ISSUE TITLE
I want shell completion for the AaC package

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#215]
As a user of AaC, I want shell tab-completion for AaC commands, so that I don't have to repetitively type out commands or copy-paste them in my shell.

## AC:
- [ ] The user is able to type `aac valid` in a shell, hit tab, then see it completed to `aac validate`
- [ ] There is autocompletion for file paths (This may require changes to the current argparse configuration)

## Notes:
* The main library contender I found for this is [argcomplete](https://kislyuk.github.io/argcomplete/)
  * Limited non-bash support: `You’re using bash as your shell (limited support for zsh, fish, and tcsh is available)`

**Comment by cvchaparro** [comment]
Another option that supports bash and zsh: https://dvc.org/blog/shtab-completion-release

**Comment by Coffee2Bits** [comment]
Tracking this task in a newer story #409
