### ISSUE TITLE
Add yaml metadata to Parser output

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#240]
In order to support the heavily contextual nature of LSP features, we need to add some contextual information to our parsed definitions. Each definition should include some information to support document-level references at first.

## AC:
- [x] A metadata structure is for parsed definitions
  - [x] Each parsed definition/model should be wrapped in an encompassing data structure that includes metadata
- [x] Each parsed definition/model data structure must include:
  - [x] The absolute path to the file containing the definition
  - [x] The first line of the definition
  - [x] The last line of the definition
  - [x] The parsed definition/model
- [x] The parser is updated to populate the metadata structures

## Notes:
The closest support I can find from PyYaml for correlating metadata to YAML content is to use YAML scanning and tokens which seems about as effective as writing our own logic to correlate definitions to YAML string positions.

**Comment by cvchaparro** [comment]
We could also look at using PyYAML's [Mark](https://github.com/yaml/pyyaml/blob/8cdff2c80573b8be8e8ad28929264a913a63aa33/lib/yaml/error.py#L4-L43) class for this. Obviously, there will be some untangling since it seems they only use it for errors, but I think it could give us a good start.
