### ISSUE TITLE
Create the Unique Names validation plugin 

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#279]
Create the "Unique Names" validator plugin. This validator plugin verifies that every definition has a unique name. 

## AC:
- [ ] The validator plugin implements the following plugin hooks
  - [ ] `get_plugin_aac_definitions()`
  - [ ] `register_validators()`
- [ ] The validator contains acceptance scenarios for
  - [ ]  validation success
  - [ ]  validation failure
- [ ] Validation fails if another definitions in a context shares the same name
- [ ] The validation is tied to the data definition and should be applied to every definition

**Comment by cvchaparro** [comment]
This seems to basically achieve the same thing as #270. Closing as duplicate.

**Comment by Coffee2Bits** [comment]
> This seems to basically achieve the same thing as #270. Closing as duplicate.

Whoops! Thanks for catching that. We can repurpose any of these duplicate plugin stories, I have a couple more validator plugin ideas. 💡
