### ISSUE TITLE
I Want the VSCode Extension to Support Connecting to LSP Servers via TCP

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#293]
As a user of the AaC LSP and VSCode extension, I want the VSCode Extension to Support connecting to LSP servers via TCP, so that I can opt to use a local AaC LSP server or a remote AaC LSP server.

Food for thought: How can we get the extension to rety remote connections if they fail? The user can reload the window to effectively restart the extension, but we'll want to keep in mind the usability of that.

blocked by #227 

## AC:
- [x] The VSCode Extension has additional configuration settings
    - [x] LSP Server Mode
        - [x]  IO or TCP
    - [x] TCP Server Address
        - [x] Host and Port configuration options
        - [x] Host defaults to localhost value `127.0.0.1`
        - [x] Port defaults to `5007` 
- [x] If the extension is configured for IO mode, it runs the AaC LSP in IO mode
- [x] If the extension is configured for TCP mode, it connects to an LSP server via TCP
    - [x] If connection fails, an error message is reported to the user

**Comment by cvchaparro** [comment]
I don't think local mode would imply using the IO server. If we're allowing this configuration, then setting up local could indicate that I want to use the local TCP server (i.e. localhost). Additionally, saying `127.0.0.1` is remote server mode is counter-intuitive, IMO.

**Comment by Coffee2Bits** [comment]
https://github.com/itemis/xtext-languageserver-example/blob/9bbefcaf566cb88365736653bc036944bdc62504/vscode-extension/src/extension.ts#L14-L21
