### ISSUE TITLE
Investigate how to communicate AaC Language information and content to VSCode custom editors

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#308]
Investigate how to communicate AaC Language information and content to VSCode custom editors. The goal is to identify how we can supply information to a custom editor about the AaC DSL model that's driven by the LSP.

Note:
* One possible, last ditch option could be to compile the AaC package to webassembly and embed the resulting AaC WASM artifact into the VSCode extension.
  * This would allow the VSCode extension to leverage any part of the AaC python package that has an exposed web assembly interface
  * [Using WASM in a VSCode extension](https://john-millikin.com/extending-vscode-with-webassembly) 
  * [Docs on compiling python to WASM](https://pythondev.readthedocs.io/wasm.html)

## AC:
- [x] Identify and document possible methods of transferring data from the AaC python package to the custom editor
  - [x] Rest API
  - [x] VSCode API
  - [x] Web Assembly API
- [x] Identify the dependencies for implementing the possible data transferral methods 
- [x] Documentation is added to the project wiki

**Comment by Coffee2Bits** [comment]
Custom editor documentation: https://code.visualstudio.com/api/extension-guides/custom-editors#customeditor-vs-customtexteditor

Some thoughts:
* VSCode Custom editor supplies a document model and a view. The CustomTextEditor uses the underlying VSCode text document model, but with a custom visualization. This can be used to provide a basic visualization of yaml content for initial MVP.
* VSCode Custom editor with a custom document model could be used if the custom document model was set to the output of the AaC package's `print-active-context` command. If the underlying text document model contains the entirety of the active context model, then the visualization of the whole language context can be performed without communicating over a REST API with the AaC python package.

**Comment by cvchaparro** [comment]
See wiki page [here](https://github.com/jondavid-black/AaC/wiki/Communication-Layer-for-Python-Package-and-VSCode-Extension)

**Comment by Coffee2Bits** [comment]
> See wiki page [here](https://github.com/jondavid-black/AaC/wiki/Communication-Layer-for-Python-Package-and-VSCode-Extension)

Great job, thanks!
