### ISSUE TITLE
Investigate model visualization options

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#309]
Investigate and document options and requirements for model visualization in the VSCode extension. These visualization options will address questions such as:
* What does a visualized definition look like? 
* What visual delineation needs to occur for various root keys?
* What kind of visualization options are out there?
* Should we attempt to match visualization styles found in modeling software like cameo?
  * What would be the effort level to support multiple types of visualization? (Traditional UML vs Custom definition visualization?)
  
 Notes:
 * It would be helpful to reach-out to some of our potential users and discuss the desire/need for UML diagramming vs custom diagramming
 * [React Diagrams](https://github.com/projectstorm/react-diagrams)

## AC:
- [x] Identify and document the various diagramming JS libraries
  - [x] Identify interactive diagramming libraries
  - [x] Align library functionality with upcoming model visualization features 
    - [x] CRUD Operations
    - [x] Interactivity
    - [x] UML diagramming support

**Comment by cvchaparro** [comment]
See the wiki [here](https://github.com/jondavid-black/AaC/wiki/Visualization-Libraries-for-AaC)

**Comment by cvchaparro** [comment]
I still need to create a simple example with each option.
