### ISSUE TITLE
Create an LSP testing and assertion framework 

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#326]
Currently, testing the LSP is tricky to test which presents an obvious gap in testing and quality. Therefore, we need to create/identify some functions, patterns, or existing tools that will vastly improve the ability to test the LSP features.

## AC:
- [x] The testing framework is capable of easily creating and managing virtual/temporary documents
- [x] The testing framework provides a clear, simplified API for triggering events as the LSP client
- [x] The testing framework provides common assertion functions
  - [x] Abstract away the need to dig through LSP responses
- [x] Create a unit test class that handles the setup/tear down associated with LSP tests

**Comment by cvchaparro** [comment]
This is for Haskell, but could be a good reference for ideas: https://hackage.haskell.org/package/lsp-test

**Comment by Coffee2Bits** [comment]
Rolling to sprint 4
