### ISSUE TITLE
Validate primitives

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#329]
As a modeler, I want validation to ensure my primitive types are valid so that I get immediate feedback on errors in my model content.

AC:

- [x] Must ensure types identified as int are in fact integer values.
- [x] Must ensure types identified as numbers are in fact decimal values
- [x] Must ensure types identified as boolean are in fact true or false values
- [x] Must ensure types identified as date do in fact parse as date values values
- [x] Must ensure types identified as file are in fact existing files

Note:  Not sure if/how we would validate the map type.  Is the map type even needed or used?  Also not sure there's any real validation to be done for strings other than maybe ensuring it is not empty.

**Comment by Coffee2Bits** [comment]
Considering this addressed by the linked PRs.
