### ISSUE TITLE
I want go to definition for the AaC DSL

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#349]
As a user of the AaC LSP server, I want go to definition implemented, so that I can easily find the definition of items in the AaC language.

## AC:
- [x] Users can look up the definition of AaC definitions via the definition's name
- [x] Users can look up the root-key definitions via selecting the root key
- [x] When a user looks up an AaC definition via the LSP, the IDE opens an editor with the file containing the target `schema` definition

**Comment by cvchaparro** [comment]
Ref: [Goto Definition Request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_definition) in the LSP specification.
