### ISSUE TITLE
I want the plugins to derive their command information from their definition model

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#436]
As a plugin developer, I want the plugins to drive their command information via their definition model, so that I don't have to 

Idea: Have the Gen-plugin auto-generate an enum, reference, a hook, or an interface that the implementations can easily hook on/implement.

## AC:
- [ ] All information in the `AacCommand` class and its arguments are driven by the data in the plugin's model
- [ ] The only model-driven attribute is the command callback, which an implementation can be registered to
  - [ ] There are multiple implementations here

**Comment by lizzcondrey** [comment]
This is a duplicate story of #605 that was completed, so this can be closed out.
