### ISSUE TITLE
I Want General Plugin Developer Documentation

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#437]
As an AaC plugin developer, I want some documentation on how to build/use AaC plugins.

## AC:
- [x] Contribution Points are documented
  - [x] Name
  - [x] Description of the content
  - [x] Description/Context of what the data is used for/the impact of it 
- [x] Describe the components of the auto-generated Plugin structure
  - [x] \_\_init__.py
  - [x] implementation file
  - [x] Plugin architecture file
  - [x] Adding Jinja templates for generation plugins
- [x] How to generate a plugin using the gen-plugin command
- [x] How to build, unit test, and integration test the plugin
- [x] How to install a plugin and test it with via the AaC CLI

**Comment by JustAChucklin** [comment]
I can pick this up
@Coffee2Bits , @cvchaparro

**Comment by JustAChucklin** [comment]
Is this needing to be a new document? Or should we add on to the existing docs that are there?

**Comment by Coffee2Bits** [comment]
> @Coffee2Bits , @cvchaparro Is this needing to be a new document? Or should we add on to the existing docs that are there?
> 
> I was looking through the existing ones that are there and I am thinking that this would be better to be its own doc. Thoughts?

This would be good as an independent page under the dev_guide.

**Comment by JustAChucklin** [comment]
I have a question that I can bring up tomorrow regarding the integration test of the generated plugin. I am not sure if this is covered or not already without my knowledge. 

Will be linking a PR in the morning.
