### ISSUE TITLE
Convert the definition_helpers module to definitions.collections

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#446]
The module [aac.lang.definition_helpers.py](https://github.com/jondavid-black/AaC/blob/main/python/src/aac/lang/definition_helpers.py) is composed of collection-related functions that would make more sense in a `collections` module under `aac.lang.definitions`. 

## AC: 
- [x] The module `aac.lang.definition_helpers` is moved to `aac.lang.definitions.collections`
- [x] References to the module are updated
- [x] Uses of `list` and `filter` are replaced with list comprehension + filtering
- [x] The LanguageContext delegates to the new `collections` package where possible

## Additional Resources:
[Python how to use comprehension with if statements.](https://pythonguides.com/python-list-comprehension-using-if-else/)

[Module to migrate](https://github.com/jondavid-black/AaC/blob/3c97aea699ab8be74c6aff3dc2877a6c929f3a20/python/src/aac/lang/definition_helpers.py)

**Comment by alexacole** [comment]
I would love to work on this. Please assign me this issue.

**Comment by Coffee2Bits** [comment]
> I would love to work on this. Please assign me this issue.

Hi Alexacole! We really appreciate your interest and willingness to contribute to Architecture-as-Code, however, we unfortunately currently [have some constraints](https://github.com/jondavid-black/AaC#note-to-contributors) for who can contribute at the moment.

Take care!

**Comment by Coffee2Bits** [comment]
Moving to HIP as Chuck is out.

**Comment by JustAChucklin** [comment]
Picking this up

**Comment by JustAChucklin** [comment]
@Coffee2Bits , is there an example you have for the 3rd criterion for this?

If I am not misunderstanding I think this is already being done?

**Comment by JustAChucklin** [comment]
Nevermind see the example now
