### ISSUE TITLE
I want the LSP Rename to support enum values

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#449]
As an AaC user, I want the LSP Rename to support enum values, so that I can easily change enum values and their use.

## AC:
- [x] When rename is performed on an enum value symbol, all instances of the enum value are updated
- [x] When rename is performed on a enum value symbol, enum value is updated in its parent definition

**Comment by JustAChucklin** [comment]
Picking this up @Coffee2Bits
