### ISSUE TITLE
Document how to profile the AaC Python Package

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#464]
I want developer and plugin-developer documentation on how to profile my AaC application or plugin.

## Reference:
[cProfile/Profile documentation](https://docs.python.org/3/library/profile.html)

## AC:
- [x] Document how to use `cProfile` or `Profile` alternatively is cProfile isn't installed.
  - [x] Document why we would want to use cProfile instead of Profile for speed.
- [x] Document how to profile AaC commands
- [x] Document how to profile plugins (as a plugin-developer)
- [x] Document how to glean basic information output
- [x] This new documentation lives in the developer documentation

**Comment by JustAChucklin** [comment]
I am wondering if this can be put into another doc under the dev_docs directory if the docs become too long
@Coffee2Bits , @cvchaparro , thoughts?

**Comment by Coffee2Bits** [comment]
> I am wondering if this can be put into another doc under the dev_docs directory if the docs become too long @Coffee2Bits , @cvchaparro , thoughts?

Absolutely. In fact, I'd prefer this be a separate doc under the Dev Guide. If you have issues with the depth of documents in the right-hand navigation menu, let me know and we'll see what we can do.

**Comment by Coffee2Bits** [comment]
> @Coffee2Bits Gotcha, perfect. That is the route I was thinking of going but was wanting to make sure that it was ok to do.
> 
> Another question. For the examples that I am going to be giving. I am wondering if there is a specific plugin that should be used as an example for the cProfile and Profile packages

Hmm, the click CLI change does change how we execute the commands and those old notes I made. Why don't you give it a try with Gen-design-doc or Gen-protobuf since both of those spend some time computing and generating artifacts. I would document using the profile around the pre-generated entry points for plugin commands/callbacks, like here https://github.com/jondavid-black/AaC/blob/2a29543e1630edd52f82f63d1f9609f9a5621551/python/src/aac/plugins/first_party/gen_design_doc/gen_design_doc_impl.py#L48-L49
