### ISSUE TITLE
Air-gap Install Doesn't Work

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#513]
When running the air-gap installation from the 0.1.5 release the following error is encountered.

`ERROR: Could not find a version that satisfies the requirement markupsafe==2.1.1 (from versions: none)
ERROR: No matching distribution found for markupsafe==2.1.1`

To Replicate:
- Install new Linux VM (same error occurs  with both Fedora and Ubuntu)
- Verify python3 version
- Install pip using the get-pip.py method
- Unzip the "latest-ubuntu" AaC release file
- Follow instructions for air-gap install in the README

**Comment by jondavid-black** [comment]
Maybe not appropriate to address in a bug, but would using pyinstaller to create a self-contained aac executable be a simpler solution for air-gapped installation?

**Comment by Coffee2Bits** [comment]
> Maybe not appropriate to address in a bug, but would using pyinstaller to create a self-contained aac executable be a simpler solution for air-gapped installation?

It sounds like PyInstaller wouldn't be compatible with our plugin framework since pluggy leverages pip to automatically register/install AaC plugins. 

I'm able to replicate this issue in a container-based installation. Pydantic and Markupsafe are both dependencies with compiled c code, as indicated by their names `MarkupSafe-2.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl` and `pydantic-1.10.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`. It seems like these 'manylinux' dependencies are either out of date (2014?!) or not as generally compatible as their names seem to indicate. When I try to individually install pydantic, I get this error:
```
$pip install aac_secure_install_0.1.5/pydantic-1.10.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl 
ERROR: pydantic-1.10.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

This is similar to some of the early hurdles I had with integrating python packages with pre-compiled c code when putting this together. I'll need to do some more research on how we can get around this.

In the meantime, are you able to install markupsafe manually via `pip install aac_secure_install_0.1.5/MarkupSafe-2.1.1*.whl` or do you also get the message `MarkupSafe-2.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.`?

**Comment by jondavid-black** [comment]
On the Ubuntu desktop VM the pip version is 22.3.1 (Python 3.10).  Installing the Markupsafe week from the aac release does result in the error message you have above.

**Comment by jondavid-black** [comment]
On the Ubuntu VM, I was curious if the online install would work.  Running pip install aac works with no problem.

I then did a pip uninstall aac and attempted the air-gap install again.  It failed again, this time complaining about pydantic.  Seems like more evidence that the issue is with the pre-compiled c dependencies.

**Comment by jondavid-black** [comment]
I attempted the same approach described for ubuntu on an brand new Fedora 37 Workstation VM.  In this instance I was unable to download the wheels and received the following error output:
```
ERROR: Cannot install aac==0.0.1, aac==0.0.3, aac==0.0.4, aac==0.0.5, aac==0.1.1, aac==0.1.2, aac==0.1.3, aac==0.1.4 and aac==0.1.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    aac 0.1.5 depends on MarkupSafe>=2.1
    aac 0.1.4 depends on iteration-utilities>=0.11
    aac 0.1.3 depends on iteration-utilities>=0.11
    aac 0.1.2 depends on iteration-utilities>=0.11
    aac 0.1.1 depends on iteration-utilities>=0.11
    aac 0.0.5 depends on iteration-utilities>=0.11
    aac 0.0.4 depends on iteration-utilities>=0.11
    aac 0.0.3 depends on coverage==6.0
    aac 0.0.1 depends on coverage==6.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
After getting this error I did a standard `pip install aac` and it completed without any issues.

**Comment by Coffee2Bits** [comment]
> I attempted the same approach described for ubuntu on an brand new Fedora 37 Workstation VM. In this instance I was unable to download the wheels and received the following error output:
> 
> ```
> ERROR: Cannot install aac==0.0.1, aac==0.0.3, aac==0.0.4, aac==0.0.5, aac==0.1.1, aac==0.1.2, aac==0.1.3, aac==0.1.4 and aac==0.1.5 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     aac 0.1.5 depends on MarkupSafe>=2.1
>     aac 0.1.4 depends on iteration-utilities>=0.11
>     aac 0.1.3 depends on iteration-utilities>=0.11
>     aac 0.1.2 depends on iteration-utilities>=0.11
>     aac 0.1.1 depends on iteration-utilities>=0.11
>     aac 0.0.5 depends on iteration-utilities>=0.11
>     aac 0.0.4 depends on iteration-utilities>=0.11
>     aac 0.0.3 depends on coverage==6.0
>     aac 0.0.1 depends on coverage==6.0
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> ```
> 
> After getting this error I did a standard `pip install aac` and it completed without any issues.

I assume that output is what you got from running the secure install script? I'm a little confused since I wouldn't expect an index-less install to report on previous versions of AaC being incompatible...

Is this still the 3.11 pip environment? I've noticed some issues with the current project management setup in 3.11, so I'm also investigating a new build process that's 3.11 compatible.

**Comment by jondavid-black** [comment]
Actually no, that's what I get when running `python3 -m pip download --only-binary :all: --dest . --no-cache aac` in an attempt to pull down wheels that I could use with the script.  I expected to be able to replicate what I did on Ubuntu within a Red Hat type environment, but I got that error instead.  That said, I agree that it seems strange to see references to the old versions.

**Comment by jondavid-black** [comment]
All that said, I was able to successfully install from PyPI use NG pip in all cases.  It's just the air gap that seems to create issues.

**Comment by Coffee2Bits** [comment]
I created a PR #515 with some changes to how we create the secure install archive. I'm able to leverage pip to pull down the python 3.9, 3.10, and 3.11 versions of AaC's dependencies into the secure installation, and it's now working in the ubuntu container image I linked above when I set the python version to 3.10 or 3.11.

Are you able to use this secure install package [(secure_install_ubuntu-20.04.zip)](https://github.com/jondavid-black/AaC/files/10424029/secure_install_ubuntu-20.04.zip), or the most recent one from the PR pipeline to test in your environments to confirm this is the fix?

**Comment by jondavid-black** [comment]
I'm on travel and don't have access to my laptop for a few days...maybe the week if the snow storm predicted for Denver is as bad as they say it may be.

**Comment by Coffee2Bits** [comment]
> I'm on travel and don't have access to my laptop for a few days...maybe the week if the snow storm predicted for Denver is as bad as they say it may be. But I may have an alternative...let's see.

Ok, no worries.

**Comment by jondavid-black** [comment]
I was able to download and successfully install!!!  I've got an environment problem with my python ssh install I need to resolve before we claim complete success, but I think that's on me.   I'll do a full python reinstall tonight and try again.

**Comment by jondavid-black** [comment]
I tested the new air-gap installer on a fresh install of Fedora Workstation 37 with python version  3.11.0 present by default.  I installed pip using the package manager.  I then followed the aac air-gap install using the package linked above.  I got no errors!  
```
[jd@fedora aac_secure_install_0.1.5]$ aac version
0.1.5
```
I think we can call this complete.   Thank you!
