### ISSUE TITLE
Run unit tests in parallel

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#534]
As a developer, I want to speed up the pipeline execution so I get feedback faster.

Currently we run unit tests using tox which delegates to nose2.  We do not have it setup to run tests in parallel, but nose2 allows you do do that by using the following command `nose2 -c tox.ini --plugin=nose2.plugins.mp -N 10` to spawn 10 parallel threads for running tests.  A simple runtime comparison was done, by comparing the duration of the command from the last successful pipeline run, which took 511.019s, to a multi-threaded run using the command above in a 16 core GitPod environment, which took 121.636s co complete.  If this same speedup can be achieved in the pipelines, we'd cut ~6.5 minutes out of each unit test execution within the pipeline.  We would have to ensure there's nothing else going on that compromises the quality / stability of the tests and the coverage reporting.

AC:

- [ ] Configure unit tests to run in parallel.
- [ ] Ensure the tests are still run as expected and complete successfully.

**Comment by Coffee2Bits** [comment]
I don't recall exactly what the initial blocker was, but we couldn't get this to work the first time around. Seems like I got around whatever that original blocker was; this is such a nice improvement!
