### ISSUE TITLE
Generate Bill of Materials (BOM)

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#544]
As a physical architecture modeler, I want a command that generates a BOM when it is given a material deployment model so that I can provide it to procurement.

AC:

- [x] Must add "gen-bom" command to the material plugin.
- [x] Must produce a csv with a line item for each part grouped by location (i.e. quantity summed so that there is 1 part line for each site).

**Comment by jondavid-black** [comment]
This was weird...

I was trying to do some super basic plugin definition stuff and couldn't get anything work work.  I'd run `aac gen-bom filename.yaml` and instead of getting the "not implemented" message I'd get a "command doesn't exist".  I instrumented things and saw that the plugin was being registered correctly.  I eventually realized that the material-model plugin was inactive for some reason.  I don't know why, or how it became inactive.  It is actually the only first party plugin that was inactive.  I was able to activate the plugin from the command line and things now work as expected, but the fact I had to do this was strange.  Need to understand what was going on with that situation.

**Comment by Coffee2Bits** [comment]
> This was weird...
> 
> I was trying to do some super basic plugin definition stuff and couldn't get anything work work. I'd run `aac gen-bom filename.yaml` and instead of getting the "not implemented" message I'd get a "command doesn't exist". I instrumented things and saw that the plugin was being registered correctly. I eventually realized that the material-model plugin was inactive for some reason. I don't know why, or how it became inactive. It is actually the only first party plugin that was inactive. I was able to activate the plugin from the command line and things now work as expected, but the fact I had to do this was strange. Need to understand what was going on with that situation.

Since this is a story, I'll assume that you're working off the main branch. We just re-enabled persistence and disabling/enabling plugins so that users can curate the commands and plugins they see, which sounds like the behavior you're seeing. The new plugin being inactive happens because there is a state file that is tracking the active plugins, and new plugins are inactive by default. If you use ephemeral environments like Gitpod, each fresh instance activates all the plugins by default, or you can remove the `state.json` file.

I'll be adding this info to the release notes.

**Comment by jondavid-black** [comment]
I'm actually just adding a command to the existing material modeling plugin.  Maybe that one was somehow disabled by default for some reason.  I did create a branch from main yesterday morning, so your through process is probably correct.

**Comment by jondavid-black** [comment]
I decided to take some liberty with the 2nd AC.  It seems that the user (like me) would actually want to see things aggregated by deployment and assembly.  This way we don't lose the contextual information around the existence of the part by overly aggregating things.  A pet peeve of mine is getting a BOM, trying to review it, and not having a clue what the actual material items are designated for usage within the material model, so I wanted the BOM to remain descriptive in that regard.
