### ISSUE TITLE
I want a primitive string validation

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#550]
As an AaC user, I want a primitive validation for string, so that I can guarantee that string values are actually strings.

There is a question of how do we validate strings; the goal for this validator is to ensure that fields of type 'string' are represented as strings in the python environment. This will help us to avoid issues where plugin developers are expecting to be able to perform python string operations on a field that is designated as a string with the confidence that the value won't be a non-string object.

## References:
Example integer primitive validator: https://github.com/jondavid-black/AaC/blob/ebe8651472afa136a37994cdf728c2af53e9c34a/python/src/aac/plugins/first_party/primitive_type_check/validators/int_validator.py#L1-L49

## AC:
- [ ] There is a new primitive type validation for strings
- [ ] The string primitive validation ensures that string are instances of python string objects.
- [ ] If a user puts a non-valid value in a string field, their validation fails with an appropriate error message.
  - [ ] The message must include a note about surrounding the offending value with quotations to turn it into a string value.

**Comment by cvchaparro** [comment]
For simplicity, I'll work this in PR #542.
