### ISSUE TITLE
Feasibility research - SysML Plugin converting to and from alternative formats

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#551]
Feasibility research - SysML Plugin converting to and from alternative formats

The goal is to determine if we can support converting to and from the XMI or exported SysML format with AaC SysML.

## AC:

- XMI-focused work:
  - [x] Collect some example XMI files
  - [x] Identify the conversion path from XMI to AaC SysML
  - [x] Identify the conversion path from AaC SysML to XMI
  - [x] Identify any information that can't be captured in the converted materials
  - [x] Identify any python tools or libraries that would aid in parsing XMI files and outputting XMI files.
  - [x] Identify blockers and the scope of work necessary to support the effort
  - [x] The output of this research is captured as a part of this story.
- SysML-focused work:
  - [x] Collect some example SysML files
  - [x] Identify the conversion path from SysML's exported format to AaC SysML
  - [x] Identify the conversion path from AaC SysML to SysML's exported
  - [x] Identify any information that can't be captured in the converted materials
  - [x] Identify any python tools or libraries that would aid in parsing exported SysML files and outputting to SysML files.
  - [x] Identify blockers and the scope of work necessary to support the effort
  - [x] The output of this research is captured as a part of this story.

**Comment by Coffee2Bits** [comment]
I need to capture some XMI sources I found. Where better than here? 😄 
* [https://www.omg.org/spec/SysML/20080501/SysML-profile.xmi](XMI v2.1 for SysML)
* [Frontpage for the XMI standard from OMG](http://www.omg.org/spec/XMI/)

**Comment by lizzcondrey** [comment]
[SysMLPluginFeasibility.pdf](https://github.com/jondavid-black/AaC/files/11490878/SysMLPluginFeasibility.pdf)
