### ISSUE TITLE
I want AaC v0.1.X to v0.2.0 Breaking Changes and Mitigations Documented

### ISSUE THREAD

**Issue by Coffee2Bits** [jondavid-black/AaC#603]
As an AaC user and plugin developer, I want AaC v0.1.X to v0.2.0 Breaking Changes and Mitigations Documented, so that I have accessible resource on how to overcome issues stemming from the DSL updates.

AC:
- [x] The change from `model` to `Plugin` for plugin definitions is documented
  - [x] Changes necessary to migrate old plugins from `model` to `Plugin` are documented
- [x] The updated Core Spec style is documented
  - [ ] Changes necessary to migrate old definitions are documented 
- [x] The updated `import` clause change is documented
  - [x] Changes necessary to migrate old definitions are documented
- [x] All changes are documented in a new github page titled `AaC Breaking Changes and Mitigations`
  - [x] Each version transition is given a section. (Only 0.1 to 0.2 for now)

**Comment by lizzcondrey** [comment]
Here is the wiki page for the [V0.2.0 documentation](https://github.com/jondavid-black/AaC/wiki/Release-v0.2.0) of this task.
