### ISSUE TITLE
User Interface MVP

### ISSUE THREAD

**Issue by jondavid-black** [jondavid-black/AaC#7]
As a system modeler I want a user interface that allows me to easily build a system model from top-down.

AC:
- [ ] Implement wireframes from #64 
- [x] Start the UI from an aac command `$ aac ui`

**Comment by Coffee2Bits** [comment]
I was able to implement almost all of the wireframe, but there are some limitations within tkinter that need a lot more time and effort to implement. I wasn't able to implement scroll windows, it looks like it requires some extra tampering to implement ([example gist](https://gist.github.com/JackTheEngineer/81df334f3dcff09fd19e4169dd560c59)), and the buttons/marks aren't as stylized as the wireframe.
